version: '3.4'
services:
  # Typesense search service
  typesense:
    image: typesense/typesense:0.25.2

    restart: on-failure

    ports:
      - "127.0.0.1:8108:8108"

    volumes:
      # Set TYPESENSE_HOST_DATA_DIR to the path of the data directory on local
      # host machine. Defaults to ./typesense-data in search application directory
      - ${TYPESENSE_HOST_DATA_DIR:-./typesense-data}:${TYPESENSE_DATA_DIR}
      
    # The `command` option should only include Typesence CLI options, which are
    # appended to default Typesense image ENTRYPOINT: `/opt/typesense-server`
    #
    # TYPESENSE_SERVER_API_KEY is required (server will fail without it) in order
    # to set the master admin API key used when calling Typesense APIs.
    command: '--data-dir=${TYPESENSE_DATA_DIR} --api-key=${TYPESENSE_SERVER_API_KEY} --enable-cors'
