version: '3.4'
services:
  # Typesense search service
  typesense:
    image: typesense/typesense:0.25.1
    restart: on-failure
    ports:
      - "127.0.0.1:8108:8108"
    volumes:
      - ${TYPESENSE_DATA:-./typesense-data}:/data
    env_file:
      - $PWD/typesense.env
    command: sh start_typesense.sh